# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# python-doc bot, 2025
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.10\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-09-13 16:59+0000\n"
"PO-Revision-Date: 2025-09-12 23:37+0000\n"
"Last-Translator: python-doc bot, 2025\n"
"Language-Team: Portuguese (Brazil) (https://app.transifex.com/python-doc/"
"teams/5390/pt_BR/)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % "
"1000000 == 0 ? 1 : 2;\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "Exceções"

#: ../../library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr "**Código-fonte:** :source:`Lib/asyncio/exceptions.py`"

#: ../../library/asyncio-exceptions.rst:16
msgid "The operation has exceeded the given deadline."
msgstr "A operação excedeu o prazo estabelecido."

#: ../../library/asyncio-exceptions.rst:19
msgid ""
"This exception is different from the builtin :exc:`TimeoutError` exception."
msgstr "Esta exceção é diferente da exceção embutida :exc:`TimeoutError`."

#: ../../library/asyncio-exceptions.rst:25
msgid "The operation has been cancelled."
msgstr "A operação foi cancelada."

#: ../../library/asyncio-exceptions.rst:27
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""
"Esta exceção pode ser capturada para executar operações personalizadas "
"quando as tarefas assíncronas são canceladas. Em quase todas as situações, a "
"exceção deve ser levantada novamente."

#: ../../library/asyncio-exceptions.rst:33
msgid ":exc:`CancelledError` is now a subclass of :class:`BaseException`."
msgstr ":exc:`CancelledError` é agora uma subclasse de :class:`BaseException`."

#: ../../library/asyncio-exceptions.rst:38
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr "Estado interno inválido de :class:`Task` ou :class:`Future`."

#: ../../library/asyncio-exceptions.rst:40
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr ""
"Pode ser levantada em situações como definir um valor de resultado para um "
"objeto *Future* que já tem um valor de resultado definido."

#: ../../library/asyncio-exceptions.rst:46
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""
"A *syscall* \"sendfile\" não está disponível para o soquete ou tipo de "
"arquivo fornecido."

#: ../../library/asyncio-exceptions.rst:49
msgid "A subclass of :exc:`RuntimeError`."
msgstr "Uma subclasse de :exc:`RuntimeError`."

#: ../../library/asyncio-exceptions.rst:54
msgid "The requested read operation did not complete fully."
msgstr "A operação de leitura solicitada não foi totalmente concluída."

#: ../../library/asyncio-exceptions.rst:56
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr "Levantada pelas :ref:`APIs de fluxo de asyncio<asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:58
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr "Esta exceção é uma subclasse de :exc:`EOFError`."

#: ../../library/asyncio-exceptions.rst:62
msgid "The total number (:class:`int`) of expected bytes."
msgstr "O número total (:class:`int`) de bytes esperados."

#: ../../library/asyncio-exceptions.rst:66
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr ""
"Uma string de :class:`bytes` lida antes do final do fluxo ser alcançado."

#: ../../library/asyncio-exceptions.rst:71
msgid "Reached the buffer size limit while looking for a separator."
msgstr "Atingiu o limite de tamanho do buffer ao procurar um separador."

#: ../../library/asyncio-exceptions.rst:73
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr "Levantada pelas :ref:`APIs de fluxo de asyncio <asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:77
msgid "The total number of to be consumed bytes."
msgstr "O número total de bytes a serem consumidos."
